#!/bin/bash

set -e

TARGET_NAME="libwallet_core_rs.a"
TARGET_XCFRAMEWORK_NAME=../swift/WalletCoreRs.xcframework
BUILD_FOLDER=../rust/target
CRATE="wallet-core-rs"
HEADER_NAME="WalletCoreRSBindgen.h"
TARGET_ARCH="$1"
BUILD_LOCATION="$2"


create_xc_framework() {
  rm -rf $TARGET_XCFRAMEWORK_NAME
  xcodebuild -create-xcframework -library $BUILD_FOLDER/$TARGET_NAME -library $BUILD_FOLDER/darwin_universal/$TARGET_NAME -library $BUILD_FOLDER/aarch64-apple-ios/release/$TARGET_NAME -output $TARGET_XCFRAMEWORK_NAME
  mkdir -p $TARGET_XCFRAMEWORK_NAME/ios-arm64_x86_64-maccatalyst
  cp $BUILD_FOLDER/catalyst/$TARGET_NAME $TARGET_XCFRAMEWORK_NAME/ios-arm64_x86_64-maccatalyst
}

cd rust


if [[ "$TARGET_ARCH" == "android" ]]; then
    echo "Generating Android targets"
    cargo build --target aarch64-linux-android --target armv7-linux-androideabi --target x86_64-linux-android --target i686-linux-android --release
elif [[ "$TARGET_ARCH" == "ios" ]]; then
    if [ `uname` == "Darwin" ]; then
        echo "Generating iOS targets"
        cargo build --target aarch64-apple-ios --target aarch64-apple-ios-sim --target x86_64-apple-ios --target aarch64-apple-darwin --target x86_64-apple-darwin --release &
        cargo +nightly build -Z build-std --target aarch64-apple-ios-macabi --target x86_64-apple-ios-macabi --release &
        wait
        lipo $BUILD_FOLDER/x86_64-apple-ios/release/$TARGET_NAME $BUILD_FOLDER/aarch64-apple-ios-sim/release/$TARGET_NAME -create -output $BUILD_FOLDER/$TARGET_NAME
        mkdir -p $BUILD_FOLDER/darwin_universal
        lipo $BUILD_FOLDER/x86_64-apple-darwin/release/$TARGET_NAME $BUILD_FOLDER/aarch64-apple-darwin/release/$TARGET_NAME -create -output $BUILD_FOLDER/darwin_universal/$TARGET_NAME
        mkdir -p $BUILD_FOLDER/catalyst
        lipo $BUILD_FOLDER/aarch64-apple-ios-macabi/release/$TARGET_NAME $BUILD_FOLDER/x86_64-apple-ios-macabi/release/$TARGET_NAME -create -output $BUILD_FOLDER/catalyst/$TARGET_NAME
    
        create_xc_framework
    fi
else
    # TODO - See how to fit single arch from IOS
    if [[ "$TARGET_ARCH" == "arm64-v8a" ]]; then 
        cargo build --target aarch64-linux-android --release
    elif [[ "$TARGET_ARCH" == "x86" ]]; then 
        cargo build --target i686-linux-android --release
    elif [[ "$TARGET_ARCH" == "armeabi-v7a" ]]; then 
        cargo build --target armv7-linux-androideabi --release
    elif [[ "$TARGET_ARCH" == "x86_64" ]]; then 
        cargo build --target x86_64-linux-android --release
    elif [[ "$TARGET_ARCH" == "x86_64" ]]; then 
        cargo build --target x86_64-linux-android --release
    else
	    # TODO - This was called if not "android" before, not sure if correct then or now 
        echo "Generating Native targets"
        cargo build --release
        cargo build --target wasm32-unknown-emscripten --release --verbose
    fi

fi


cbindgen --crate $CRATE --output ../src/rust/bindgen/$HEADER_NAME
cd -

# TODO - Is this necessary? CMake can just use the output directly. Only reason is to put binaries in the build directory
#[[ -e rust/target/release/${TARGET_NAME} ]] && cp rust/target/release/${TARGET_NAME} $2/lib/
#[[ -e rust/target/i686-linux-android/release/${TARGET_NAME} ]] && cp rust/target/i686-linux-android/release/${TARGET_NAME} $2/lib/
#[[ -e rust/target/x86_64-linux-android/release/${TARGET_NAME} ]] && cp rust/target/x86_64-linux-android/release/${TARGET_NAME} $2/lib/
#[[ -e rust/target/wasm32-unknown-emscripten/release/${TARGET_NAME} ]] && cp rust/target/wasm32-unknown-emscripten/release/${TARGET_NAME} $2/lib/
#[[ -e rust/target/armv7-linux-androideabi/release/${TARGET_NAME} ]] && cp rust/target/armv7-linux-androideabi/release/${TARGET_NAME} $2/lib/
#[[ -e rust/target/aarch64-linux-android/release/${TARGET_NAME} ]] && cp rust/target/aarch64-linux-android/release/${TARGET_NAME} $2/lib/

if [[ `uname` == "Darwin" ]] && [[ "$1" != "android" ]]; then
cd rust
cat > $TARGET_XCFRAMEWORK_NAME/Info.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AvailableLibraries</key>
	<array>
		<dict>
			<key>LibraryIdentifier</key>
			<string>macos-arm64_x86_64</string>
			<key>LibraryPath</key>
			<string>libwallet_core_rs.a</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
				<string>x86_64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>macos</string>
		</dict>
		<dict>
        			<key>LibraryIdentifier</key>
        			<string>ios-arm64_x86_64-maccatalyst</string>
        			<key>LibraryPath</key>
        			<string>libwallet_core_rs.a</string>
        			<key>SupportedArchitectures</key>
        			<array>
        				<string>arm64</string>
        				<string>x86_64</string>
        			</array>
        			<key>SupportedPlatform</key>
        			<string>ios</string>
        			<key>SupportedPlatformVariant</key>
        			<string>maccatalyst</string>
        </dict>
		<dict>
			<key>LibraryIdentifier</key>
			<string>ios-arm64</string>
			<key>LibraryPath</key>
			<string>libwallet_core_rs.a</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
		</dict>
		<dict>
			<key>LibraryIdentifier</key>
			<string>ios-arm64_x86_64-simulator</string>
			<key>LibraryPath</key>
			<string>libwallet_core_rs.a</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
				<string>x86_64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
			<key>SupportedPlatformVariant</key>
			<string>simulator</string>
		</dict>
	</array>
	<key>CFBundlePackageType</key>
	<string>XFWK</string>
	<key>XCFrameworkFormatVersion</key>
	<string>1.0</string>
</dict>
</plist>
EOF
cd -
fi
